### ISSUE TITLE
Error with SSID settings

### ISSUE THREAD

**Issue by scul81** [AndrewBudziszek/bitcoin-ticker-esp8266#1]
Hi,

Sorry for the other issue I wasn't aware that you had a specific library for the ESP8266 also.

I just compiled this code and created secrets.h as instructed but the code crashes on the following;
`Arduino: 1.8.13 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

CryptoTicker:13:20: error: 'SECRET_SSID' was not declared in this scope

   13 | const char* ssid = SECRET_SSID;

      |                    ^~~~~~~~~~~

CryptoTicker:14:24: error: 'SECRET_WIFI_PASSWORD' was not declared in this scope; did you mean 'WIFI_PASSWORD'?

   14 | const char* password = SECRET_WIFI_PASSWORD;

      |                        ^~~~~~~~~~~~~~~~~~~~

      |                        WIFI_PASSWORD

exit status 1

'SECRET_SSID' was not declared in this scope

`

**Comment by AndrewBudziszek** [comment]
Hi, are you sure the `secrets.h` file is in the same directory as your .ino file? I verified that the code is still working on my end.

**Comment by scul81** [comment]
Yes the file is in the same location as the .ino file. I fail to see why it refuses to load it

**Comment by AndrewBudziszek** [comment]
@scul81 Do you have your code uploaded on github? If so, can you send me the link to your code? Make sure to redact your actually SSID password

**Comment by AndrewBudziszek** [comment]
Hi, @scul81 let's try to figure this part out first. Let me know when you get the code uploaded. Thanks for your patience on this. I really appreciate that you're continuing to follow through. :)

**Comment by scul81** [comment]
Hey @SonnyBrooks thanks, I have uploaded my code here.
https://github.com/scul81/crypto

Thank you for your patience and support.

**Comment by AndrewBudziszek** [comment]
@scul81 I fixed the secrets issue. I updated my repository to fix the bug. I've also gone ahead and fixed it in your repo. Let me know if it works.

**Comment by scul81** [comment]
Thanks that does resolve this problem.
