### ISSUE TITLE
Error with HTTPClient

### ISSUE THREAD

**Issue by scul81** [AndrewBudziszek/bitcoin-ticker-esp8266#2]
When running the code I receive the following error

```

Arduino: 1.8.13 (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, dtr (aka nodemcu), 26 MHz, 40MHz, DOUT (compatible), 1MB (FS:64KB OTA:~470KB), 2, nonos-sdk 2.2.1+100 (190703), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

D:\Data\Docs\Arduino\CryptoTicker\CryptoTicker.ino: In function 'void loop()':

CryptoTicker:71:15: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)

   71 |     http.begin(url);

      |     ~~~~~~~~~~^~~~~

CryptoTicker:105:17: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)

  105 |       http.begin(historyURL);

      |       ~~~~~~~~~~^~~~~~~~~~~~

exit status 1

call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)


```

I can confirm I have correctly installed the ESP8266 library

**Comment by AndrewBudziszek** [comment]
@scul81 Were any other changes made to the code? You might be missing an import. Please link your code if possible.

**Comment by scul81** [comment]
Certainly.. the code has been copy pasted

[cryptoino.txt](https://github.com/SonnyBrooks/bitcoin-ticker-esp8266/files/6859561/cryptoino.txt)

**Comment by AndrewBudziszek** [comment]
@scul81 Please upload your project to github, or copy paste that code here - https://gist.github.com/. This makes it easier to collaborate.

You have the code for the secrets file commented out. 

Your code:
```
//const char* ssid = SECRET_SSID;
//const char* password = SECRET_WIFI_PASSWORD;

const char* ssid = "xxx";
const char* password = "xxx";
```



Delete the last two lines and uncomment the first two lines.

That might be unrelated but that's the first thing that sticks out to me.

**Comment by scul81** [comment]
Yes I commented those out because the secrets file doesn't work and I have no other option but to hardcode these strings as per issue #1  - I can upload my code on github

**Comment by AndrewBudziszek** [comment]
@scul81 Can you confirm that you are targeting the right board in the Tools menu?
![image](https://user-images.githubusercontent.com/8484828/127930455-575492e7-6a01-4834-8cf9-071ee26043e9.png)

**Comment by scul81** [comment]
![esp8266](https://user-images.githubusercontent.com/86270359/127932306-d4471656-571d-4a7e-ad9a-0cf00f0e469f.png)

as above

The error remains (also after resolving the secrets file problem)

**Comment by scul81** [comment]
Would you like to see the contents of my library folder or shall I remove all libraries and reinstall the recommend ones?
It would be nice if you could give direct links or references to the libraries with version number and author to make sure they match

**Comment by AndrewBudziszek** [comment]
Hmm try this?

![image](https://user-images.githubusercontent.com/8484828/127932694-90558835-01d6-420f-ba32-b853d68a577c.png)

**Comment by scul81** [comment]
![esp_http](https://user-images.githubusercontent.com/86270359/127932941-fb987639-cce8-4082-a77f-a60e4953e7df.PNG)
same result unfortunately

**Comment by AndrewBudziszek** [comment]
Can you check the board version?

Tools >> Board >> Board Manager

![image](https://user-images.githubusercontent.com/8484828/127935339-c8fb70a2-7062-458e-9a52-96a61274b1bf.png)

**Comment by AndrewBudziszek** [comment]
It looks like it breaks with the latest version of that package. So this one might work.

**Comment by scul81** [comment]
It seems to have compiled fine! I will now try and test to see if I can load it to the unit

**Comment by AndrewBudziszek** [comment]
Yay! I will update the documentation. Sorry for the trouble!

**Comment by scul81** [comment]
That's OK I believe we can close this issue now
