### ISSUE TITLE
Display malfunctioning

### ISSUE THREAD

**Issue by scul81** [AndrewBudziszek/bitcoin-ticker-esp8266#5]
OK so now that we have fixed the code issues I am having a controller/hardware issue it seems.

![2021-08-03 11 42 31](https://user-images.githubusercontent.com/86270359/127936868-adde77f6-3fe7-4f15-9a67-305ac40d06dc.jpg)

I am using the following components:
https://www.aliexpress.com/item/32665100123.html?spm=a2g0s.12269583.0.0.7406d564z2463j
https://www.aliexpress.com/item/32683094040.html?spm=a2g0s.12269583.0.0.6882ec17YBFqvG

I have set the screen address to 0x3D for the 128x64 screen.

I have connected pins: 
D1 to SCK
D2 to SDA
V to VDD
G to GND

**Comment by AndrewBudziszek** [comment]
Closing as this is a possible hardware issue - not software.
